name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Compilar y ejecutar tests
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v7

      - name: Instalar .NET 10
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restaurar paquetes
        run: dotnet restore ECommerce.slnx

      - name: Compilar
        run: dotnet build ECommerce.slnx --no-restore --configuration Release

      - name: Ejecutar tests
        run: dotnet test ECommerce.slnx --no-build --configuration Release
